CREATE TABLE [dbo].[Level]
(
	[LevelId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] VARCHAR(128) NOT NULL, 
    [Description] VARCHAR(128) NULL, 
    [IsDeleted] BIT NOT NULL DEFAULT 0
)
