DELETE FROM Level
DELETE FROM LevelConfiguration
DELETE FROM Organisation
delete from OrganisationInvite
DELETE FROM OrganisationMembership
DELETE FROM PasswordReset
DELETE FROM Scoreboard
DELETE FROM Target
DELETE FROM TargetAppearance
DELETE FROM TargetZone
DELETE FROM UserAccount